### PR TITLE
Configurations

### PR DESCRIPTION
**Pull request by wbyoung**
I don't know how much of this you'll want to take, but these were the change that I need to make in order to get bwoken to work with a project I'm working on.

Rake not picking up the build task for me may be an issue with my system or version of rake that I'm using, so that may or may not affect others. It also may just be that I'm not entirely familiar with Rake and I'm missing something.

Using a project was simple enough. It looks like that was already set up, but it was just throwing an exception for because the workspace string was nil.

It seems Xcode may have moved the location of the automation script in an upcoming version. Also, using xcode-select to figure out where Xcode stuff lives helped out for me since I didn't have it at the standard location (looks like you already have that in the pipeline, though).

The most important thing for me was that my project failed to build because `GCC_PREPROCESSOR_DEFINITIONS` was overriding my preprocessor definitions. I don't think it's possible to use inherit on the command line so I added an xcconfig file.

I hope some of this can make its way into bwoken. Thanks for sharing this great project!

### CODE REVIEW

**Comment by listrophy** [comment]
Thanks Whitney. I just upgraded to Xcode 4.4, and I'm noticing some odd behavior myself. I'll see about pulling in your changes, but we will need the tests to pass.

Also, I'm gonna need to find some time to hack on bwoken soon. :)

**Comment by listrophy** [comment]
I'd prefer not to change the command line interface... Could you try again with "build" instead of "compile"? Perhaps you were tripped up by something else. Technically, it's doing a build, not just compilation. :)

**Comment by wbyoung** [comment]
When I change it back, `rake build -v --trace` tells me:

> *\* Invoke build (first_time, not_needed)

But with _compile_, `rake compile -v --trace` tells me:

> *\* Invoke compile (first_time)
> *\* Execute compile

And then actually works.

**Comment by wbyoung** [comment]
My project builds to a `build` directory which seems to be the problem. It seems like rake is treating this as a file rather than a task, but it's using the build directory's modification date to determine that it doesn't need to execute build.

**Comment by listrophy** [comment]
Oh snap. You nailed it. We define a directory task called 'build' and a real task called 'build'. D'oh!

**Comment by wbyoung** [comment]
Is the directory task for build even needed?

**Comment by listrophy** [comment]
Yes, the directory task for build is needed.

**Pull request merged**
