### PR TITLE
Safely handle PTYs, better exit code handling.

### PR DESCRIPTION
**Pull request by tcoulter**
Instead of using a hard coded PTY, let Ruby take care of it for you. As well, remove the ugly stack trace for test failures -- keeping the trace and exception for more serious errors -- and propagate exit codes down to the parent so you can continue to use bwoken with Jenkins, etc.

### CODE REVIEW

**Comment by tcoulter** [comment]
Looks like I have tests to fix. Coming soon.

**Comment by tbugai** [comment]
This works awesomely on my machine, but when used on Travis CI it fails to run the tests for some reason.

**Comment by tcoulter** [comment]
Weird. I didn't see that it failed. Let me see what I can do.

**Comment by tcoulter** [comment]
Hi @tbugai. That's what I thought - I knew I had fixed those tests before. The commit "Fix tests" passed on TravisCI, after it originally failed. It should be good to go right?

**Comment by tbugai** [comment]
I'm sorry, I wasn't clear enough.  I'm using bwoken to test an app on Travis CI.  It is during the testing of that app that I get the issue.  Before your pull request, I would get a "Failed to connect to local pid watcher" error.  When I tried to use you're pull request, it passes but never runs any of the tests.  

https://travis-ci.org/tbugai/grocery-list/builds/6712262

**Comment by metalshreds** [comment]
Did you ever resolve this issue? Now that Travis-CI machines are up and running Xcode 5 we are running into this error.

"Failed to connect to local pid watcher service: (os/kern) failure"

https://travis-ci.org/ARISGames/iOSClient

Any help is appreciated, thank you!

**Comment by tcoulter** [comment]
I haven't, sorry. Since this PR I've left the company that was exploring bwoken; haven't gotten the opportunity to revisit it.

**Comment by metalshreds** [comment]
Thanks for taking the time to reply. I'll keep looking.

**Pull request closed without merging**
